#include "country_specifier_builder.hpp"

namespace generator
{
namespace regions
{
std::unique_ptr<CountrySpecifier> CountrySpecifierBuilder::MakeCountrySpecifier(
std::string const & country) const
{
  auto it = m_specifiers.find(country);
  if (it == m_specifiers.end())
  {
    LOG(LWARNING, ("Country", country, "has not specifier, look at generator/regions/specs"));
    return std::make_unique<CountrySpecifier>();
  }

  return it->second();
}
}  // namespace regions
}  // namespace generator

#include "generator/regions/specs/afghanistan.inl"
#include "generator/regions/specs/albania.inl"
#include "generator/regions/specs/algeria.inl"
#include "generator/regions/specs/andorra.inl"
#include "generator/regions/specs/angola.inl"
#include "generator/regions/specs/antigua_and_barbuda.inl"
#include "generator/regions/specs/argentina.inl"
#include "generator/regions/specs/aruba.inl"
#include "generator/regions/specs/australia.inl"
#include "generator/regions/specs/austria.inl"
#include "generator/regions/specs/azerbaijan.inl"
#include "generator/regions/specs/bahamas.inl"
#include "generator/regions/specs/bahrain.inl"
#include "generator/regions/specs/bangladesh.inl"
#include "generator/regions/specs/barbados.inl"
#include "generator/regions/specs/belarus.inl"
#include "generator/regions/specs/belgium.inl"
#include "generator/regions/specs/belize.inl"
#include "generator/regions/specs/benin.inl"
#include "generator/regions/specs/bhutan.inl"
#include "generator/regions/specs/bolivia.inl"
#include "generator/regions/specs/bosnia_and_herzegovina.inl"
#include "generator/regions/specs/brazil.inl"
#include "generator/regions/specs/brunei.inl"
#include "generator/regions/specs/bulgaria.inl"
#include "generator/regions/specs/burkina_faso.inl"
#include "generator/regions/specs/burundi.inl"
#include "generator/regions/specs/cameroon.inl"
#include "generator/regions/specs/canada.inl"
#include "generator/regions/specs/chad.inl"
#include "generator/regions/specs/chile.inl"
#include "generator/regions/specs/china.inl"
#include "generator/regions/specs/colombia.inl"
#include "generator/regions/specs/costa_rica.inl"
#include "generator/regions/specs/cote_divoire.inl"
#include "generator/regions/specs/croatia.inl"
#include "generator/regions/specs/cuba.inl"
#include "generator/regions/specs/cyprus.inl"
#include "generator/regions/specs/czech_republic.inl"
#include "generator/regions/specs/denmark.inl"
#include "generator/regions/specs/dominican_republic.inl"
#include "generator/regions/specs/egypt.inl"
#include "generator/regions/specs/estonia.inl"
#include "generator/regions/specs/ethiopia.inl"
#include "generator/regions/specs/finland.inl"
#include "generator/regions/specs/france.inl"
#include "generator/regions/specs/french_polynesia.inl"
#include "generator/regions/specs/gabon.inl"
#include "generator/regions/specs/gambia.inl"
#include "generator/regions/specs/georgia.inl"
#include "generator/regions/specs/germany.inl"
#include "generator/regions/specs/ghana.inl"
#include "generator/regions/specs/greece.inl"
#include "generator/regions/specs/guinea.inl"
#include "generator/regions/specs/haiti.inl"
#include "generator/regions/specs/hong_kong.inl"
#include "generator/regions/specs/hungary.inl"
#include "generator/regions/specs/iceland.inl"
#include "generator/regions/specs/india.inl"
#include "generator/regions/specs/indonesia.inl"
#include "generator/regions/specs/iran.inl"
#include "generator/regions/specs/iraq.inl"
#include "generator/regions/specs/ireland.inl"
#include "generator/regions/specs/isle_of_man.inl"
#include "generator/regions/specs/israel.inl"
#include "generator/regions/specs/italy.inl"
#include "generator/regions/specs/japan.inl"
#include "generator/regions/specs/jordan.inl"
#include "generator/regions/specs/kosovo.inl"
#include "generator/regions/specs/laos.inl"
#include "generator/regions/specs/latvia.inl"
#include "generator/regions/specs/lebanon.inl"
#include "generator/regions/specs/lesotho.inl"
#include "generator/regions/specs/liberia.inl"
#include "generator/regions/specs/libya.inl"
#include "generator/regions/specs/lithuania.inl"
#include "generator/regions/specs/luxembourg.inl"
#include "generator/regions/specs/macedonia.inl"
#include "generator/regions/specs/madagascar.inl"
#include "generator/regions/specs/malawi.inl"
#include "generator/regions/specs/malaysia.inl"
#include "generator/regions/specs/mali.inl"
#include "generator/regions/specs/mauritania.inl"
#include "generator/regions/specs/moldova.inl"
#include "generator/regions/specs/morocco.inl"
#include "generator/regions/specs/mozambique.inl"
#include "generator/regions/specs/myanmar.inl"
#include "generator/regions/specs/nepal.inl"
#include "generator/regions/specs/netherlands.inl"
#include "generator/regions/specs/new_zealand.inl"
#include "generator/regions/specs/niger.inl"
#include "generator/regions/specs/nigeria.inl"
#include "generator/regions/specs/north_korea.inl"
#include "generator/regions/specs/norway.inl"
#include "generator/regions/specs/philippines.inl"
#include "generator/regions/specs/poland.inl"
#include "generator/regions/specs/portugal.inl"
#include "generator/regions/specs/romania.inl"
#include "generator/regions/specs/russia.inl"
#include "generator/regions/specs/senegal.inl"
#include "generator/regions/specs/serbia.inl"
#include "generator/regions/specs/sierra_leone.inl"
#include "generator/regions/specs/slovakia.inl"
#include "generator/regions/specs/slovenia.inl"
#include "generator/regions/specs/south_africa.inl"
#include "generator/regions/specs/south_korea.inl"
#include "generator/regions/specs/south_sudan.inl"
#include "generator/regions/specs/suriname.inl"
#include "generator/regions/specs/swaziland.inl"
#include "generator/regions/specs/sweden.inl"
#include "generator/regions/specs/switzerland.inl"
#include "generator/regions/specs/syria.inl"
#include "generator/regions/specs/taiwan.inl"
#include "generator/regions/specs/tajikistan.inl"
#include "generator/regions/specs/tanzania.inl"
#include "generator/regions/specs/thailand.inl"
#include "generator/regions/specs/the_central_african_republic.inl"
#include "generator/regions/specs/togo.inl"
#include "generator/regions/specs/tunisia.inl"
#include "generator/regions/specs/turkey.inl"
#include "generator/regions/specs/uganda.inl"
#include "generator/regions/specs/ukraine.inl"
#include "generator/regions/specs/united_kingdom.inl"
#include "generator/regions/specs/united_states.inl"
#include "generator/regions/specs/vanuatu.inl"
#include "generator/regions/specs/vietnam.inl"
