#pragma once

#include "partners_api/taxi_countries.hpp"

namespace taxi
{
namespace places
{
// Places which are enabled for yandex taxi and in the same time are disabled for uber taxi.
Countries const kPlaces = {
    {{"Armenia", {"Yerevan"}},
     {"Belarus", {"Minsk"}},
     {"Georgia Region", {"Tbilisi"}},
     {"Kazakhstan", {"Almaty", "Astana", "Karaganda", "Pavlodar", "Shymkent"}},
     {"Russian Federation",
      {"Almetyevsk",
       "Anapa",
       "Aprelevka",
       "Arzamas",
       "Arkhangelsk",
       "Astrakhan",
       "Balakovo",
       "Balashikha",
       "Barnaul",
       "Belgorod",
       "Blagoveshchensk",
       "Bryansk",
       "Vidnoye",
       "Vladivostok",
       "Vladikavkaz",
       "Vladimir",
       "Volgograd",
       "Volgodonsk",
       "Vologda",
       "Voronezh",
       "Gelendzhik",
       "Golitsyno",
       "Dedovsk",
       "Dzerzhinsky",
       "Dmitrov",
       "Dolgoprudny",
       "Domodedovo",
       "Dubna",
       "Yekaterinburg",
       "Zheleznodorozhny",
       "Zhukovsky",
       "Zelenograd",
       "Ivanovo",
       "Ivanteyevka",
       "Izhevsk",
       "Irkutsk",
       "Yoshkar-Ola",
       "Kazan",
       "Kaliningrad",
       "Kaluga",
       "Kamensk-Uralsky",
       "Kashira",
       "Kemerovo",
       "Kirov",
       "Kislovodsk",
       "Kolomna",
       "Komsomolsk-on-Amur",
       "Korolyov",
       "Kotelniki",
       "Krasnogorsk",
       "Krasnodar",
       "Krasnoznamensk",
       "Krasnoyarsk",
       "Kurgan",
       "Kursk",
       "Lipetsk",
       "Lobnya",
       "Lytkarino",
       "Lyubertsy",
       "Magnitogorsk",
       "Makhachkala",
       "Mozhaisk",
       "Moscow",
       "Murmansk",
       "Mytishchi",
       "Naberezhnye Chelny",
       "Naro-Fominsk",
       "Nakhabino",
       "Nizhnekamsk",
       "Nizhny Novgorod",
       "Nizhny Tagil",
       "Novokuznetsk",
       "Novorossiysk",
       "Novosibirsk",
       "Novy Urengoy",
       "Noginsk",
       "Noyabrsk",
       "Obninsk",
       "Odintsovo",
       "Ozyory",
       "Omsk",
       "Oryol",
       "Orenburg",
       "Orsk",
       "Penza",
       "Perm",
       "Petrozavodsk",
       "Podolsk",
       "Pushkino",
       "Ramenskoye",
       "Reutov",
       "Rostov-on-Don",
       "Ryazan",
       "Samara",
       "Saint Petersburg",
       "Saransk",
       "Saratov",
       "Sergiyev Posad",
       "Serpukhov",
       "Smolensk",
       "Sochi",
       "Stavropol",
       "Staraya Kupavna",
       "Sterlitamak",
       "Stupino",
       "Surgut",
       "Syzran",
       "Syktyvkar",
       "Taganrog",
       "Tambov",
       "Tver",
       "Tolyatti",
       "Tomsk",
       "Troitsk",
       "Tula",
       "Tyumen",
       "Ulan-Ude",
       "Ulyanovsk",
       "Ufa",
       "Fryazino",
       "Khabarovsk",
       "Khimki",
       "Cheboksary",
       "Chelyabinsk",
       "Cherepovets",
       "Chekhov",
       "Chita",
       "Shchyolkovo",
       "Elektrostal",
       "Elektrougli",
       "Yakutsk",
       "Yaroslavl"}}}};
}  // namespace places
}  // namespace taxi
