#include "AppResourceId.h"


const wchar_t* IDC_ABOUT_BUTTON = L"IDC_ABOUT_BUTTON";
const wchar_t* IDC_CLOSE_BUTTON = L"IDC_CLOSE_BUTTON";
const wchar_t* IDC_ENABLE_SCALE_BUTTONS_CB = L"IDC_ENABLE_SCALE_BUTTONS_CB";
const wchar_t* IDC_FOOTS_CHECKBUTTON = L"IDC_FOOTS_CHECKBUTTON";
const wchar_t* IDC_MEASUREMENT_NOTE = L"IDC_MEASUREMENT_NOTE";
const wchar_t* IDC_MEASUREMENT_UNITS_LABEL = L"IDC_MEASUREMENT_UNITS_LABEL";
const wchar_t* IDC_METERS_CHECKBUTTON = L"IDC_METERS_CHECKBUTTON";
const wchar_t* IDC_VERSION_LABEL = L"IDC_VERSION_LABEL";
const wchar_t* IDC_WEB = L"IDC_WEB";
const wchar_t* IDF_ABOUT_FORM = L"IDF_ABOUT_FORM";
const wchar_t* IDF_ABOUT_FORM1 = L"IDF_ABOUT_FORM1";
const wchar_t* IDS_ABOUT = L"IDS_ABOUT";
const wchar_t* IDS_CANCEL = L"IDS_CANCEL";
const wchar_t* IDS_KILOMETRES = L"IDS_KILOMETRES";
const wchar_t* IDS_MEASUREMENT_UNITS = L"IDS_MEASUREMENT_UNITS";
const wchar_t* IDS_MEASUREMENT_UNITS_SUMMARY = L"IDS_MEASUREMENT_UNITS_SUMMARY";
const wchar_t* IDS_MILES = L"IDS_MILES";
const wchar_t* IDS_PREF_ZOOM_SUMMARY = L"IDS_PREF_ZOOM_SUMMARY";
const wchar_t* IDS_PREF_ZOOM_TITLE = L"IDS_PREF_ZOOM_TITLE";
const wchar_t* IDS_VERSION = L"IDS_VERSION";
