plugins {
  id 'com.android.library'
}

apply from: "${rootProject.rootDir}/groovy/common-config.gradle"
apply from: "${rootProject.rootDir}/groovy/publishing.gradle"

android {
  namespace 'app.organicmaps.sdk.car'
  // enableKotlin = true  // see app/build.gradle

  defaultConfig {
    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
  }

  compileOptions {
    coreLibraryDesugaringEnabled = true
  }
}

dependencies {
  api project(':sdk')
  api libs.androidx.car.app

  implementation project(':sdk:widgets:speedlimit')
  implementation project(':sdk:widgets:lanes')

  coreLibraryDesugaring libs.android.tools.desugaring

  testImplementation libs.androidx.junit
  androidTestImplementation libs.androidx.junit
  androidTestImplementation libs.androidx.test.runner
}

Publish(project, [
    'artifactId' : 'car',
    'name'       : 'Organic Maps SDK for Android Auto and Android Automotive',
    'description': 'A library that provides Organic Maps integration for Android Auto and Android Automotive'
])
