#pragma once

//#define TEST_ADS_REMOVAL_IDS
//#define TEST_BOOKMARK_INAPP_IDS
//#define STAGE_BOOKMARKS_CATALOG_SERVER
//#define STAGE_CLOUD_SERVER
//#define STAGE_LOCALS_SERVER
//#define STAGE_PASSPORT_SERVER
//#define STAGE_PURCHASE_SERVER
//#define STAGE_UGC_SERVER
//#define STAGE_DLINKS
//#define STAGE_BOOKING_EXTENDED_INFO
//#define STAGE_PICTURES_SERVER
//#define STAGE_ALOHALYTICS_SERVER
//#define STAGE_TRACKING_HISTORICAL_SERVER
// Integer values of percents are only supported.
//#define TEST_CROWN_PERCENT_OF_DEVICES
