#pragma once

//#define TEST_ADS_REMOVAL_IDS
//#define STAGE_BOOKMARKS_CATALOG_SERVER
//#define STAGE_CLOUD_SERVER
//#define STAGE_LOCALS_SERVER
//#define STAGE_PASSPORT_SERVER
//#define STAGE_PURCHASE_SERVER
//#define STAGE_UGC_SERVER
//#define STAGE_DLINKS
