plugins {
  id 'com.android.library'
}

apply from: "${rootProject.rootDir}/groovy/common-config.gradle"
apply from: "${rootProject.rootDir}/groovy/publishing.gradle"

android {
  namespace 'app.organicmaps.sdk.widgets.lanes'
  // enableKotlin = true  // see app/build.gradle

  defaultConfig {
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

  compileOptions {
    coreLibraryDesugaringEnabled = true
  }
}

dependencies {
  api project(':sdk')

  coreLibraryDesugaring libs.android.tools.desugaring

  implementation libs.androidx.annotation
  implementation libs.androidx.appcompat

  androidTestImplementation libs.androidx.junit
  androidTestImplementation libs.androidx.test.runner
}

Publish(project, [
    'artifactId' : 'widgets-lanes',
    'name'       : 'Organic Maps SDK. Lanes widget',
    'description': 'A library that provides a lanes widget for the Organic Maps SDK'
])
