// This file is autogenerated
#import "UIColorRoutines.h"
#import "UIColor+PartnerColor.h"

@implementation UIColor (PartnerColor)
+ (UIColor *)partner1Background
{
  return [UIColor colorWithRed:scaled(48) green:scaled(52) blue:scaled(56) alpha:1];
}
+ (UIColor *)partner1TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:1];
}
+ (UIColor *)partner3Background
{
  return [UIColor colorWithRed:scaled(230) green:scaled(23) blue:scaled(23) alpha:1];
}
+ (UIColor *)partner3TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:1];
}
+ (UIColor *)partner4Background
{
  return [UIColor colorWithRed:scaled(0) green:scaled(0) blue:scaled(0) alpha:100];
}
+ (UIColor *)partner4TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner6Background
{
  return [UIColor colorWithRed:scaled(0) green:scaled(92) blue:scaled(185) alpha:100];
}
+ (UIColor *)partner6TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner7Background
{
  return [UIColor colorWithRed:scaled(226) green:scaled(67) blue:scaled(7) alpha:1];
}
+ (UIColor *)partner7TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:1];
}
+ (UIColor *)partner8Background
{
  return [UIColor colorWithRed:scaled(141) green:scaled(27) blue:scaled(47) alpha:100];
}
+ (UIColor *)partner8TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner9Background
{
  return [UIColor colorWithRed:scaled(0) green:scaled(0) blue:scaled(0) alpha:1];
}
+ (UIColor *)partner9TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:1];
}
+ (UIColor *)partner10Background
{
  return [UIColor colorWithRed:scaled(2) green:scaled(81) blue:scaled(152) alpha:100];
}
+ (UIColor *)partner10TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner11Background
{
  return [UIColor colorWithRed:scaled(165) green:scaled(3) blue:scaled(0) alpha:1];
}
+ (UIColor *)partner11TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:1];
}
+ (UIColor *)partner12Background
{
  return [UIColor colorWithRed:scaled(126) green:scaled(189) blue:scaled(50) alpha:100];
}
+ (UIColor *)partner12TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner13Background
{
  return [UIColor colorWithRed:scaled(55) green:scaled(37) blue:scaled(43) alpha:100];
}
+ (UIColor *)partner13TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner14Background
{
  return [UIColor colorWithRed:scaled(0) green:scaled(0) blue:scaled(0) alpha:100];
}
+ (UIColor *)partner14TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner15Background
{
  return [UIColor colorWithRed:scaled(0) green:scaled(0) blue:scaled(0) alpha:100];
}
+ (UIColor *)partner15TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner16Background
{
  return [UIColor colorWithRed:scaled(0) green:scaled(0) blue:scaled(0) alpha:100];
}
+ (UIColor *)partner16TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner17Background
{
  return [UIColor colorWithRed:scaled(0) green:scaled(0) blue:scaled(0) alpha:100];
}
+ (UIColor *)partner17TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner18Background
{
  return [UIColor colorWithRed:scaled(0) green:scaled(185) blue:scaled(86) alpha:100];
}
+ (UIColor *)partner18TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner19Background
{
  return [UIColor colorWithRed:scaled(87) green:scaled(26) blue:scaled(140) alpha:100];
}
+ (UIColor *)partner19TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}
+ (UIColor *)partner20Background
{
  return [UIColor colorWithRed:scaled(87) green:scaled(26) blue:scaled(140) alpha:100];
}
+ (UIColor *)partner20TextColor
{
  return [UIColor colorWithRed:scaled(255) green:scaled(255) blue:scaled(255) alpha:100];
}

@end