@interface UIColor (MapsMeColor)

+ (UIColor *)primaryDark;
+ (UIColor *)primary;
+ (UIColor *)primaryLight;
+ (UIColor *)fadeBackground;
+ (UIColor *)menuBackground;
+ (UIColor *)downloadBadgeBackground;
+ (UIColor *)pressBackground;
+ (UIColor *)yellow;
+ (UIColor *)green;
+ (UIColor *)red;
+ (UIColor *)errorPink;
+ (UIColor *)orange;
+ (UIColor *)linkBlue;
+ (UIColor *)linkBlueHighlighted;
+ (UIColor *)linkBlueDark;
+ (UIColor *)buttonRed;
+ (UIColor *)buttonRedHighlighted;
+ (UIColor *)blackPrimaryText;
+ (UIColor *)blackSecondaryText;
+ (UIColor *)blackStatusBarBackground;
+ (UIColor *)blackHintText;
+ (UIColor *)blackDividers;
+ (UIColor *)white;
+ (UIColor *)whitePrimaryText;
+ (UIColor *)whitePrimaryTextHighlighted;
+ (UIColor *)whiteSecondaryText;
+ (UIColor *)whiteHintText;
+ (UIColor *)whiteDividers;
+ (UIColor *)buttonDisabledBlueText;
+ (UIColor *)buttonHighlightedBlueText;
+ (UIColor *)alertBackground;
+ (UIColor *)blackOpaque;
+ (UIColor *)bookingBackground;
+ (UIColor *)opentableBackground;
+ (UIColor *)bannerBackground;
+ (UIColor *)bannerButtonBackground;
+ (UIColor *)toastBackground;
+ (UIColor *)statusBarBackground;
+ (UIColor *)transparentGreen;
+ (UIColor *)ratingRed;
+ (UIColor *)ratingOrange;
+ (UIColor *)ratingYellow;
+ (UIColor *)ratingLightGreen;
+ (UIColor *)ratingGreen;
+ (UIColor *)partner1Background;
+ (UIColor *)partner1TextColor;
+ (UIColor *)partner3Background;
+ (UIColor *)partner3TextColor;
+ (UIColor *)partner4Background;
+ (UIColor *)partner4TextColor;
+ (UIColor *)partner5Background;
+ (UIColor *)partner5TextColor;
+ (UIColor *)partner6Background;
+ (UIColor *)partner6TextColor;
+ (UIColor *)partner7Background;
+ (UIColor *)partner7TextColor;
+ (UIColor *)partner8Background;
+ (UIColor *)partner8TextColor;
+ (UIColor *)partner9Background;
+ (UIColor *)partner9TextColor;
+ (UIColor *)partner10Background;
+ (UIColor *)partner10TextColor;
+ (UIColor *)partner11Background;
+ (UIColor *)partner11TextColor;
+ (UIColor *)partner12Background;
+ (UIColor *)partner12TextColor;
+ (UIColor *)partner13Background;
+ (UIColor *)partner13TextColor;
+ (UIColor *)partner14Background;
+ (UIColor *)partner14TextColor;
+ (UIColor *)partner15Background;
+ (UIColor *)partner15TextColor;
+ (UIColor *)partner16Background;
+ (UIColor *)partner16TextColor;
+ (UIColor *)partner17Background;
+ (UIColor *)partner17TextColor;
+ (UIColor *)partner18Background;
+ (UIColor *)partner18TextColor;
+ (UIColor *)partner19Background;
+ (UIColor *)partner19TextColor;
+ (UIColor *)partner20Background;
+ (UIColor *)partner20TextColor;

+ (UIColor *)colorWithName:(NSString *)colorName;

+ (void)setNightMode:(BOOL)mode;
+ (BOOL)isNightMode;

- (UIColor *)opposite;

+ (UIColor *)facebookButtonBackground;
+ (UIColor *)facebookButtonBackgroundDisabled;

@end
