NS_ASSUME_NONNULL_BEGIN

// Colors for Swift are autogenerated by the Xcode as a static properties.
// This category is fallback for legacy ObjC UI elements.

@interface UIColor (Colors)

+ (UIColor *)colorFromHexString:(NSString *)hexString;

+ (UIColor *)greenPrimary NS_SWIFT_UNAVAILABLE("Use UIColor.greenPrimary");
+ (UIColor *)blackPrimaryText NS_SWIFT_UNAVAILABLE("Use UIColor.blackPrimaryText");
+ (UIColor *)blackSecondaryText NS_SWIFT_UNAVAILABLE("Use UIColor.blackSecondaryText");
+ (UIColor *)blackHintText NS_SWIFT_UNAVAILABLE("Use UIColor.blackHintText");
+ (UIColor *)redPrimary NS_SWIFT_UNAVAILABLE("Use UIColor.redPrimary");
+ (UIColor *)whitePrimary NS_SWIFT_UNAVAILABLE("Use UIColor.whitePrimary");
+ (UIColor *)pressBackground NS_SWIFT_UNAVAILABLE("Use UIColor.pressBackground");
+ (UIColor *)linkBlue NS_SWIFT_UNAVAILABLE("Use UIColor.linkBlue");
+ (UIColor *)linkBlueHighlighted NS_SWIFT_UNAVAILABLE("Use UIColor.linkBlueHighlighted");
+ (UIColor *)buttonRed NS_SWIFT_UNAVAILABLE("Use UIColor.buttonRed");
+ (UIColor *)blackDividers NS_SWIFT_UNAVAILABLE("Use UIColor.blackDividers");
+ (UIColor *)whitePrimaryText NS_SWIFT_UNAVAILABLE("Use UIColor.whitePrimaryText");
+ (UIColor *)whitePrimaryTextHighlighted NS_SWIFT_UNAVAILABLE("Use UIColor.whitePrimaryTextHighlighted");
+ (UIColor *)whiteHintText NS_SWIFT_UNAVAILABLE("Use UIColor.whiteHintText");
+ (UIColor *)blackOpaque NS_SWIFT_UNAVAILABLE("Use UIColor.blackOpaque");
+ (UIColor *)bookingBackground NS_SWIFT_UNAVAILABLE("Use UIColor.bookingBackground");
+ (UIColor *)opentableBackground NS_SWIFT_UNAVAILABLE("Use UIColor.opentableBackground");

@end

NS_ASSUME_NONNULL_END
