//
//  GADNativeAppInstallAdAssetIDs.h
//  Google Mobile Ads SDK
//
//  Copyright 2017 Google Inc. All rights reserved.
//

#import <Foundation/Foundation.h>

#import <GoogleMobileAds/GoogleMobileAdsDefines.h>

GAD_ASSUME_NONNULL_BEGIN

typedef NSString *GADNativeAppInstallAssetID GAD_STRING_ENUM;

GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallHeadlineAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallCallToActionAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallIconAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallBodyAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallStoreAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallPriceAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallImageAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallStarRatingAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallAttributionIconAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallAttributionTextAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallMediaViewAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallAdChoicesViewAsset;
GAD_EXTERN GADNativeAppInstallAssetID const GADNativeAppInstallBackgroundAsset;

GAD_ASSUME_NONNULL_END
