//
//  GADUnifiedNativeAdAssetIdentifiers.h
//  Google Mobile Ads SDK
//
//  Copyright 2017 Google Inc. All rights reserved.
//

#import <Foundation/Foundation.h>

#import <GoogleMobileAds/GoogleMobileAdsDefines.h>

GAD_ASSUME_NONNULL_BEGIN

typedef NSString *GADUnifiedNativeAssetIdentifier GAD_STRING_ENUM;

GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeHeadlineAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeCallToActionAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeIconAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeBodyAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeStoreAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativePriceAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeImageAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeStarRatingAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeAdvertiserAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeMediaViewAsset;
GAD_EXTERN GADUnifiedNativeAssetIdentifier const GADUnifiedNativeAdChoicesViewAsset;

GAD_ASSUME_NONNULL_END
