#pragma once

//#define DRAW_TILE_NET
//#define DEBUG_OVERLAYS_OUTPUT

//#define CHECK_VBO_BOUNDS
//#define TRACK_POINTERS
//#define DEBUG_ANIMATIONS
//#define LINES_GENERATION_CALC_FILTERED_POINTS
//#define GPS_TRACK_SHOW_RAW_POINTS
//#define DEBUG_MESSAGE_QUEUE
//#define RENDER_DEBUG_INFO_LABELS

//#define DRAPE_MEASURER_BENCHMARK
//#define SCENARIO_ENABLE
//#define SHOW_FRAMES_STATS

#ifdef DRAPE_MEASURER_BENCHMARK

//#define RENDER_STATISTIC
//#define TILES_STATISTIC
//#define GENERATING_STATISTIC

//#define TRACK_GPU_MEM
//#define TRACK_GLYPH_USAGE

#endif
