CFLAGS = /I../src/headers/ /I./ /Ox /DWIN32 /DLTC_SOURCE /W3 /Fo$@

OBJECTS=base64_test.obj cipher_hash_test.obj der_tests.obj no_prng.obj \
dsa_test.obj ecc_test.obj mac_test.obj modes_test.obj pkcs_1_test.obj \
rsa_test.obj store_test.obj test_driver.obj x86_prof.obj katja_test.obj \
dh_test.obj misc_test.obj pkcs_1_pss_test.obj pkcs_1_oaep_test.obj \
pkcs_1_emsa_test.obj pkcs_1_eme_test.obj

tomcrypt_prof.lib: $(OBJECTS)
	lib /out:tomcrypt_prof.lib $(OBJECTS)


