#!/usr/bin/env python3
"""Generate reusable lane path SVGs and Android VectorDrawables.

Each branch starts at the top of one shared stem in a 64 by 64 viewport.
The SVG components are the platform-neutral artwork; Android draws them with
separate tints so one recommended branch can be highlighted.
"""

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SVG_DIR = ROOT / "data/lane_glyphs"
ANDROID_DIR = ROOT / "android/sdk/widgets/lanes/src/main/res/drawable"

# (centerline, arrowhead). Branch centerlines never include the shared stem.
GLYPHS = {
    "stem": ("M32,58 L32,40", None),
    "through": ("M32,40 L32,15", "M32,4 L22,19 L42,19 Z"),
    "slight_left": ("M32,40 C28,29 23,22 17,17", "M8,7 L26,11 L12,26 Z"),
    "left": ("M32,40 C31,28 25,23 18,23", "M5,23 L19,14 L19,32 Z"),
    "left_inner": ("M32,40 C32,29 29,25 25,25", "M14,25 L27,17 L27,33 Z"),
    "sharp_left": ("M32,40 C25,40 22,42 18,44", "M5,44 L18,36 L18,52 Z"),
    "reverse_left": ("M32,40 L32,27 C32,13 25,9 18,9 C9,9 6,15 6,27 L6,39", "M6,48 L0,35 L12,35 Z"),
    "slight_right": ("M32,40 C36,29 41,22 47,17", "M56,7 L38,11 L52,26 Z"),
    "right": ("M32,40 C33,28 39,23 46,23", "M59,23 L45,14 L45,32 Z"),
    "right_inner": ("M32,40 C32,29 35,25 39,25", "M50,25 L37,17 L37,33 Z"),
    "sharp_right": ("M32,40 C39,40 42,42 46,44", "M59,44 L46,36 L46,52 Z"),
    "reverse_right": ("M32,40 L32,27 C32,13 39,9 46,9 C55,9 58,15 58,27 L58,39", "M58,48 L52,35 L64,35 Z"),
}


def svg(centerline: str, head: str | None) -> str:
    lines = [
        "<!-- Generated by tools/python/generate_lane_glyphs.py; do not edit. -->",
        '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">',
        f'  <path d="{centerline}" fill="none" stroke="#fff" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
    ]
    if head:
        lines.append(f'  <path d="{head}" fill="#fff"/>')
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def vector(centerline: str, head: str | None) -> str:
    lines = [
        "<!-- Generated by tools/python/generate_lane_glyphs.py; do not edit. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="64dp"',
        '    android:height="64dp"',
        '    android:viewportWidth="64"',
        '    android:viewportHeight="64">',
        '  <path',
        f'      android:pathData="{centerline}"',
        '      android:fillColor="#00000000"',
        '      android:strokeColor="#ffffffff"',
        '      android:strokeWidth="7"',
        '      android:strokeLineCap="round"',
        '      android:strokeLineJoin="round"/>',
    ]
    if head:
        lines.extend([
            '  <path',
            f'      android:pathData="{head}"',
            '      android:fillColor="#ffffffff"/>',
        ])
    lines.append("</vector>")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    stale = []
    for name, (centerline, head) in GLYPHS.items():
        outputs = {
            SVG_DIR / f"{name}.svg": svg(centerline, head),
            ANDROID_DIR / f"ic_lane_{name}.xml": vector(centerline, head),
        }
        for path, content in outputs.items():
            if args.check:
                if not path.exists() or path.read_text() != content:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)

    if stale:
        parser.exit(1, "Stale lane glyphs:\n" + "\n".join(stale) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
