#!/usr/bin/env python3
"""Generate reusable lane path SVGs and Android VectorDrawables.

Each branch starts at the top of one shared stem in a 64 by 64 viewport.
The SVG components are the platform-neutral artwork; Android draws them with
separate tints so one recommended branch can be highlighted.
"""

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SVG_DIR = ROOT / "data/lane_glyphs"
ANDROID_DIR = ROOT / "android/sdk/widgets/lanes/src/main/res/drawable"

# (centerline, arrowhead). Branch centerlines never include the shared stem.
GLYPHS = {
    "stem": ("M32,58 L32,40", None),
    "through": ("M32,40 L32,16", "M32,0 L18,23 L46,23 Z"),
    "slight_left": ("M32,40 C27,29 21,20 15,14", "M5,3 L29,11 L10,27 Z"),
    "left": ("M32,40 C30,27 25,20 18,20", "M2,18 L20,2 L20,34 Z"),
    "left_inner": ("M32,40 C32,29 29,24 26,24", "M17,24 L29,12 L29,36 Z"),
    "sharp_left": ("M32,40 C25,40 22,42 18,43", "M1,43 L21,31 L21,55 Z"),
    "reverse_left": ("M32,40 L32,27 C32,13 25,9 18,9 C9,9 6,15 6,27 L6,40", "M6,50 L0,35 L12,35 Z"),
    "slight_right": ("M32,40 C37,29 43,20 49,14", "M59,3 L35,11 L54,27 Z"),
    "right": ("M32,40 C34,27 39,20 46,20", "M62,18 L44,2 L44,34 Z"),
    "right_inner": ("M32,40 C32,29 35,24 38,24", "M47,24 L35,12 L35,36 Z"),
    "sharp_right": ("M32,40 C39,40 42,42 46,43", "M63,43 L43,31 L43,55 Z"),
    "reverse_right": ("M32,40 L32,27 C32,13 39,9 46,9 C55,9 58,15 58,27 L58,40", "M58,50 L52,35 L64,35 Z"),
}


def svg(centerline: str, head: str | None) -> str:
    lines = [
        "<!-- Generated by tools/python/generate_lane_glyphs.py; do not edit. -->",
        '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">',
        f'  <path d="{centerline}" fill="none" stroke="#fff" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>',
    ]
    if head:
        lines.append(f'  <path d="{head}" fill="#fff"/>')
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def vector(centerline: str, head: str | None) -> str:
    lines = [
        "<!-- Generated by tools/python/generate_lane_glyphs.py; do not edit. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="64dp"',
        '    android:height="64dp"',
        '    android:viewportWidth="64"',
        '    android:viewportHeight="64">',
        '  <path',
        f'      android:pathData="{centerline}"',
        '      android:fillColor="#00000000"',
        '      android:strokeColor="#ffffffff"',
        '      android:strokeWidth="10"',
        '      android:strokeLineCap="round"',
        '      android:strokeLineJoin="round"/>',
    ]
    if head:
        lines.extend([
            '  <path',
            f'      android:pathData="{head}"',
            '      android:fillColor="#ffffffff"/>',
        ])
    lines.append("</vector>")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    stale = []
    for name, (centerline, head) in GLYPHS.items():
        outputs = {
            SVG_DIR / f"{name}.svg": svg(centerline, head),
            ANDROID_DIR / f"ic_lane_{name}.xml": vector(centerline, head),
        }
        for path, content in outputs.items():
            if args.check:
                if not path.exists() or path.read_text() != content:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)

    if stale:
        parser.exit(1, "Stale lane glyphs:\n" + "\n".join(stale) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
