#pragma once
// Compile with UCONFIG_USE_LOCAL define so this header will be included
// from uconfig.h

#define UCONFIG_NO_BREAK_ITERATION 1
#define UCONFIG_NO_COLLATION 1
#define UCONFIG_NO_CONVERSION 1
#define UCONFIG_NO_FILTERED_BREAK_ITERATION 1
#define UCONFIG_NO_FORMATTING 1
#define UCONFIG_NO_IDNA 1
#define UCONFIG_NO_LEGACY_CONVERSION 1
#define UCONFIG_NO_REGULAR_EXPRESSIONS 1
#define UCONFIG_NO_SERVICE 1
#define UNISTR_FROM_CHAR_EXPLICIT explicit
#define UNISTR_FROM_STRING_EXPLICIT explicit
#define U_CHARSET_IS_UTF8 1
#define U_COMMON_IMPLEMENTATION 1
#define U_DISABLE_RENAMING 1
#define U_ENABLE_DYLOAD 0
#define U_I18N_IMPLEMENTATION 1
#define U_NO_DEFAULT_INCLUDE_UTF_HEADERS 1
#define U_STATIC_IMPLEMENTATION 1
