#pragma once

extern const wchar_t* IDC_ABOUT_BUTTON;
extern const wchar_t* IDC_BUTTON_BLUE;
extern const wchar_t* IDC_BUTTON_BROWN;
extern const wchar_t* IDC_BUTTON_GREEN;
extern const wchar_t* IDC_BUTTON_ORANGE;
extern const wchar_t* IDC_BUTTON_PINK;
extern const wchar_t* IDC_BUTTON_PURPLE;
extern const wchar_t* IDC_BUTTON_RED;
extern const wchar_t* IDC_BUTTON_YELLOW;
extern const wchar_t* IDC_CANCEL;
extern const wchar_t* IDC_CHECKBUTTON_SHOW_ON_MAP;
extern const wchar_t* IDC_CLOSE_BUTTON;
extern const wchar_t* IDC_COPY_MARK;
extern const wchar_t* IDC_DOWNLOAD_LISTVIEW;
extern const wchar_t* IDC_EDITFIELD;
extern const wchar_t* IDC_EDITFIELD_NAME;
extern const wchar_t* IDC_EMAIL;
extern const wchar_t* IDC_ENABLE_GPS;
extern const wchar_t* IDC_ENABLE_SCALE_BUTTONS_CB;
extern const wchar_t* IDC_FOOTS_CHECKBUTTON;
extern const wchar_t* IDC_LABEL1;
extern const wchar_t* IDC_LISTVIEW;
extern const wchar_t* IDC_MEASUREMENT_NOTE;
extern const wchar_t* IDC_MEASUREMENT_UNITS_LABEL;
extern const wchar_t* IDC_MENU;
extern const wchar_t* IDC_MESSAGE;
extern const wchar_t* IDC_METERS_CHECKBUTTON;
extern const wchar_t* IDC_PANEL;
extern const wchar_t* IDC_SCROLLPANEL;
extern const wchar_t* IDC_SEARCHBAR;
extern const wchar_t* IDC_TEXTBOX;
extern const wchar_t* IDC_TEXTBOX1;
extern const wchar_t* IDC_VERSION_LABEL;
extern const wchar_t* IDC_WEB;
extern const wchar_t* IDC_ZOOM_IN;
extern const wchar_t* IDC_ZOOM_OUT;
extern const wchar_t* IDF_ABOUT_FORM;
extern const wchar_t* IDF_BMCATEGORIES_FORM;
extern const wchar_t* IDF_CATEGORY_FORM;
extern const wchar_t* IDF_DOWNLOAD_FORM;
extern const wchar_t* IDF_LICENSE_FORM;
extern const wchar_t* IDF_MAIN_FORM;
extern const wchar_t* IDF_SEARCH_FORM;
extern const wchar_t* IDF_SELECT_BM_CATEGORY_FORM;
extern const wchar_t* IDF_SELECT_COLOR_FORM;
extern const wchar_t* IDF_SHARE_POSITION_FORM;
extern const wchar_t* IDS_ABOUT;
extern const wchar_t* IDS_ADD_NEW_SET;
extern const wchar_t* IDS_AGREE;
extern const wchar_t* IDS_ARE_YOU_SURE;
extern const wchar_t* IDS_ATM;
extern const wchar_t* IDS_BANK;
extern const wchar_t* IDS_BECOME_A_PRO;
extern const wchar_t* IDS_BOOKMARKS;
extern const wchar_t* IDS_BOOKMARK_COLOR;
extern const wchar_t* IDS_BOOKMARK_SHARE_EMAIL;
extern const wchar_t* IDS_BOOKMARK_SHARE_EMAIL_SUBJECT;
extern const wchar_t* IDS_BOOKMARK_SHARE_SMS;
extern const wchar_t* IDS_CANCEL;
extern const wchar_t* IDS_CANCEL_DOWNLOAD;
extern const wchar_t* IDS_COPY_LINK;
extern const wchar_t* IDS_DELETE;
extern const wchar_t* IDS_DISAGREE;
extern const wchar_t* IDS_DONE;
extern const wchar_t* IDS_DOWNLOAD;
extern const wchar_t* IDS_DOWNLOAD_COUNTRY_FAILED;
extern const wchar_t* IDS_DOWNLOAD_MAPS;
extern const wchar_t* IDS_EDIT;
extern const wchar_t* IDS_EMAIL;
extern const wchar_t* IDS_ENTERTAINMENT;
extern const wchar_t* IDS_FOOD;
extern const wchar_t* IDS_FUEL;
extern const wchar_t* IDS_HOSPITAL;
extern const wchar_t* IDS_HOTEL;
extern const wchar_t* IDS_KILOMETRES;
extern const wchar_t* IDS_MAPS_LICENCE_INFO;
extern const wchar_t* IDS_MB;
extern const wchar_t* IDS_MEASUREMENT_UNITS;
extern const wchar_t* IDS_MEASUREMENT_UNITS_SUMMARY;
extern const wchar_t* IDS_MESSAGE;
extern const wchar_t* IDS_MILES;
extern const wchar_t* IDS_MY_POSITION_SHARE_EMAIL;
extern const wchar_t* IDS_MY_POSITION_SHARE_EMAIL_SUBJECT;
extern const wchar_t* IDS_MY_POSITION_SHARE_SMS;
extern const wchar_t* IDS_NO_INTERNET_CONNECTION_DETECTED;
extern const wchar_t* IDS_NO_SEARCH_RESULTS_FOUND;
extern const wchar_t* IDS_NO_WIFI_ASK_CELLULAR_DOWNLOAD;
extern const wchar_t* IDS_PARKING;
extern const wchar_t* IDS_PHARMACY;
extern const wchar_t* IDS_POLICE;
extern const wchar_t* IDS_POST;
extern const wchar_t* IDS_PREF_ZOOM_SUMMARY;
extern const wchar_t* IDS_PREF_ZOOM_TITLE;
extern const wchar_t* IDS_SETTINGS;
extern const wchar_t* IDS_SHARE;
extern const wchar_t* IDS_SHARE_MY_LOCATION;
extern const wchar_t* IDS_SHOP;
extern const wchar_t* IDS_TOILET;
extern const wchar_t* IDS_TOURISM;
extern const wchar_t* IDS_TRANSPORT;
extern const wchar_t* IDS_UNKNOWN_CURRENT_POSITION;
extern const wchar_t* IDS_USE_WIFI_RECOMMENDATION_TEXT;
extern const wchar_t* IDS_VISIBLE;
extern const wchar_t* IDS_VERSION;
// main form
extern const wchar_t * IDB_MY_POSITION_NORMAL;
extern const wchar_t * IDB_MY_POSITION_PRESSED;
extern const wchar_t * IDB_MY_POSITION_SEARCH;
extern const wchar_t * IDB_SEARCH;
extern const wchar_t * IDB_STAR;
extern const wchar_t * IDB_MENU;
// main menu
extern const wchar_t * IDB_MWM_PRO;
extern const wchar_t * IDB_DOWNLOAD_MAP;
extern const wchar_t * IDB_SETTINGS;
extern const wchar_t * IDB_SHARE;
//search
extern const wchar_t * IDB_SINGLE_RESULT;
extern const wchar_t * IDB_SUGGESTION_RESULT;
//place page
extern const wchar_t * IDB_PLACE_PAGE_BUTTON;
extern const wchar_t * IDB_PLACE_PAGE_BUTTON_SELECTED;
extern const wchar_t * IDB_PLACE_PAGE_EDIT_BUTTON;
extern const wchar_t * IDB_PLACE_PAGE_COMPASS;
extern const wchar_t * IDB_PLACE_PAGE_COMPASS_BACKGROUND;
extern const wchar_t * IDB_PLACE_PAGE_COLOR_SELECTOR;
//color
extern const wchar_t * IDB_COLOR_BLUE;
extern const wchar_t * IDB_COLOR_PP_BLUE;
extern const wchar_t * IDB_COLOR_SELECT_BLUE;
extern const wchar_t * IDB_COLOR_BROWN;
extern const wchar_t * IDB_COLOR_PP_BROWN;
extern const wchar_t * IDB_COLOR_SELECT_BROWN;
extern const wchar_t * IDB_COLOR_GREEN;
extern const wchar_t * IDB_COLOR_PP_GREEN;
extern const wchar_t * IDB_COLOR_SELECT_GREEN;
extern const wchar_t * IDB_COLOR_ORANGE;
extern const wchar_t * IDB_COLOR_PP_ORANGE;
extern const wchar_t * IDB_COLOR_SELECT_ORANGE;
extern const wchar_t * IDB_COLOR_PINK;
extern const wchar_t * IDB_COLOR_PP_PINK;
extern const wchar_t * IDB_COLOR_SELECT_PINK;
extern const wchar_t * IDB_COLOR_PURPLE;
extern const wchar_t * IDB_COLOR_PP_PURPLE;
extern const wchar_t * IDB_COLOR_SELECT_PURPLE;
extern const wchar_t * IDB_COLOR_RED;
extern const wchar_t * IDB_COLOR_PP_RED;
extern const wchar_t * IDB_COLOR_SELECT_RED;
extern const wchar_t * IDB_COLOR_YELLOW;
extern const wchar_t * IDB_COLOR_PP_YELLOW;
extern const wchar_t * IDB_COLOR_SELECT_YELLOW;
//bookmark form
extern const wchar_t * IDB_EYE;
extern const wchar_t * IDB_EMPTY;
extern const wchar_t * IDB_BOOKMARK_DELETE;
extern const wchar_t * IDB_BOOKMARK_DELETE_CUR;
extern const wchar_t * IDB_V;
