# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

workspace './../../xcode/omim.xcworkspace'

target 'MAPS.ME' do
  use_frameworks!

  # Pods for MAPS.ME

end
