# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

workspace './../../xcode/omim.xcworkspace'

target 'OMaps' do
  use_frameworks!

  # Pods for OMaps
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

end
