#include "partners_api/ads/skyeng_ads.hpp"

namespace
{
std::initializer_list<std::string> const kSupportedLanguages = {"ru"};

std::initializer_list<storage::CountryId> const kSupportedCountries = {
  "Ireland_Connacht",
  "Ireland_Leinster",
  "Ireland_Munster",
  "Ireland_Northern Counties",
  "Russia_Altai Krai",
  "Russia_Altai Republic",
  "Russia_Amur Oblast",
  "Russia_Arkhangelsk Oblast_Central",
  "Russia_Arkhangelsk Oblast_North",
  "Russia_Astrakhan Oblast",
  "Russia_Bashkortostan",
  "Russia_Belgorod Oblast",
  "Russia_Bryansk Oblast",
  "Russia_Buryatia",
  "Russia_Chechen Republic",
  "Russia_Chelyabinsk Oblast",
  "Russia_Chukotka Autonomous Okrug",
  "Russia_Chuvashia",
  "Russia_Ingushetia",
  "Russia_Irkutsk Oblast",
  "Russia_Ivanovo Oblast",
  "Russia_Jewish Autonomous Oblast",
  "Russia_Kabardino-Balkaria",
  "Russia_Kaliningrad Oblast",
  "Russia_Kaluga Oblast",
  "Russia_Kamchatka Krai",
  "Russia_Karachay-Cherkessia",
  "Russia_Kemerov Oblast",
  "Russia_Khabarovsk Krai",
  "Russia_Khakassia",
  "Russia_Kirov Oblast",
  "Russia_Komi Republic",
  "Russia_Kostroma Oblast",
  "Russia_Krasnoyarsk Krai_North",
  "Russia_Krasnoyarsk Krai_South",
  "Russia_Kurgan Oblast",
  "Russia_Kursk Oblast",
  "Russia_Lipetsk Oblast",
  "Russia_Magadan Oblast",
  "Russia_Mari El",
  "Russia_Murmansk Oblast",
  "Russia_Nenets Autonomous Okrug",
  "Russia_Nizhny Novgorod Oblast",
  "Russia_North Ossetia-Alania",
  "Russia_Novgorod Oblast",
  "Russia_Novosibirsk Oblast",
  "Russia_Omsk Oblast",
  "Russia_Orenburg Oblast",
  "Russia_Oryol Oblast",
  "Russia_Penza Oblast",
  "Russia_Perm Krai_North",
  "Russia_Perm Krai_South",
  "Russia_Primorsky Krai",
  "Russia_Pskov Oblast",
  "Russia_Republic of Dagestan",
  "Russia_Republic of Kalmykia",
  "Russia_Republic of Karelia_North",
  "Russia_Republic of Karelia_South",
  "Russia_Republic of Mordovia",
  "Russia_Ryazan Oblast",
  "Russia_Sakha Republic",
  "Russia_Sakhalin Oblast",
  "Russia_Samara Oblast",
  "Russia_Saratov Oblast",
  "Russia_Smolensk Oblast",
  "Russia_Stavropol Krai",
  "Russia_Sverdlovsk Oblast_North",
  "Russia_Tambov Oblast",
  "Russia_Tatarstan",
  "Russia_Tomsk Oblast",
  "Russia_Tula Oblast",
  "Russia_Tuva",
  "Russia_Tver Oblast",
  "Russia_Tyumen Oblast",
  "Russia_Udmurt Republic",
  "Russia_Ulyanovsk Oblast",
  "Russia_Vladimir Oblast",
  "Russia_Volgograd Oblast",
  "Russia_Vologda Oblast",
  "Russia_Voronezh Oblast",
  "Russia_Yamalo-Nenets Autonomous Okrug",
  "Russia_Yaroslavl Oblast",
  "Russia_Yugra_Khanty",
  "Russia_Yugra_Surgut",
  "Russia_Zabaykalsky Krai",
  "UK_England_East Midlands",
  "UK_England_East of England_Essex",
  "UK_England_East of England_Norfolk",
  "UK_England_Greater London",
  "UK_England_North East England",
  "UK_England_North West England_Lancaster",
  "UK_England_North West England_Manchester",
  "UK_England_South East_Brighton",
  "UK_England_South East_Oxford",
  "UK_England_South West England_Bristol",
  "UK_England_South West England_Cornwall",
  "UK_England_West Midlands",
  "UK_England_Yorkshire and the Humber",
  "UK_Northern Ireland",
  "UK_Scotland_North",
  "UK_Scotland_South",
  "UK_Wales",
  "US_Alabama_Birmingham",
  "US_Alabama_Montgomery",
  "US_Alaska",
  "US_Arizona_Flagstaff",
  "US_Arizona_Phoenix",
  "US_Arizona_Tucson",
  "US_Arkansas_North",
  "US_Arkansas_South",
  "US_California_Bakersfield_Bakersfield",
  "US_California_Bakersfield_Lancaster",
  "US_California_Chico",
  "US_California_LA",
  "US_California_LA North",
  "US_California_Redding",
  "US_California_Sacramento_Fresno",
  "US_California_Sacramento_Sacramento",
  "US_California_Sacramento_Stockton",
  "US_California_San Diego",
  "US_California_Santa_Clara_Palo Alto",
  "US_California_Santa_Clara_Santa Cruz",
  "US_Colorado_Aspen",
  "US_Colorado_Denver",
  "US_Colorado_South",
  "US_Connecticut",
  "US_Delaware",
  "US_Florida_Gainesville",
  "US_Florida_Jacksonville",
  "US_Florida_Miami",
  "US_Florida_Orlando",
  "US_Florida_Tampa",
  "US_Georgia_Atlanta",
  "US_Georgia_Macon",
  "US_Georgia_North",
  "US_Georgia_South",
  "US_Guam",
  "US_Hawaii",
  "US_Idaho_North",
  "US_Idaho_South",
  "US_Illinois_Chickago",
  "US_Illinois_Elgin",
  "US_Illinois_Rockford",
  "US_Illinois_South",
  "US_Illinois_Springfield",
  "US_Indiana_Evansville",
  "US_Indiana_Indianapolis",
  "US_Indiana_North",
  "US_Iowa_Des Moines",
  "US_Iowa_Waterloo",
  "US_Iowa_West",
  "US_Kansas_East",
  "US_Kansas_West",
  "US_Kansas_Wichita",
  "US_Kentucky_East",
  "US_Kentucky_Louisville",
  "US_Kentucky_West",
  "US_Louisiana_Central",
  "US_Louisiana_New Orleans",
  "US_Maine",
  "US_Maryland_Baltimore",
  "US_Maryland_and_DC",
  "US_Massachusetts_Boston",
  "US_Massachusetts_Central",
  "US_Massachusetts_Plymouth",
  "US_Massachusetts_Southeastern",
  "US_Massachusetts_West",
  "US_Michigan_Detroit",
  "US_Michigan_Grand Rapids",
  "US_Michigan_Lansing",
  "US_Michigan_North",
  "US_Minnesota_Minneapolis",
  "US_Minnesota_North",
  "US_Minnesota_Rochester",
  "US_Minnesota_Saint Cloud",
  "US_Mississippi_Gulfport",
  "US_Mississippi_North",
  "US_Missouri_East",
  "US_Missouri_Kansas",
  "US_Missouri_Springfield",
  "US_Missouri_St Louis",
  "US_Montana_East",
  "US_Montana_West",
  "US_Nebraska_East",
  "US_Nebraska_West",
  "US_Nevada",
  "US_New Hampshire",
  "US_New Jersey_North",
  "US_New Jersey_South",
  "US_New Mexico_Albuquerque",
  "US_New Mexico_Roswell",
  "US_New York_East",
  "US_New York_New York",
  "US_New York_North",
  "US_New York_West",
  "US_North Carolina_Asheville",
  "US_North Carolina_Charlotte",
  "US_North Carolina_Greensboro",
  "US_North Carolina_Raleigh",
  "US_North Carolina_Wilmington",
  "US_North Carolina_Wilson",
  "US_North Dakota_Bismarck",
  "US_North Dakota_East",
  "US_North Dakota_Minot",
  "US_Ohio_Cincinnati",
  "US_Ohio_Cleveland",
  "US_Ohio_Columbus",
  "US_Ohio_Toledo",
  "US_Oklahoma_East",
  "US_Oklahoma_Oklahoma",
  "US_Oklahoma_Tulsa",
  "US_Oklahoma_West",
  "US_Oregon_Eugene",
  "US_Oregon_Portland",
  "US_Oregon_West",
  "US_Pennsylvania_Central",
  "US_Pennsylvania_Pittsburgh",
  "US_Pennsylvania_Reading",
  "US_Pennsylvania_Scranton",
  "US_Puerto Rico",
  "US_Rhode Island",
  "US_South Carolina_Charleston",
  "US_South Carolina_Columbia",
  "US_South Carolina_Florence",
  "US_South Dakota",
  "US_Tennessee_East",
  "US_Tennessee_West",
  "US_Texas_Amarillo",
  "US_Texas_Austin",
  "US_Texas_Dallas",
  "US_Texas_Houston",
  "US_Texas_Lubbock",
  "US_Texas_San Antonio",
  "US_Texas_Southwest",
  "US_Texas_Tyler",
  "US_Texas_Victoria",
  "US_Texas_Wako",
  "US_Texas_West",
  "US_United States Minor Outlying Islands",
  "US_Utah_North",
  "US_Utah_South",
  "US_Vermont",
  "US_Virginia_Alexandria",
  "US_Virginia_Lynchburg",
  "US_Virginia_Norfolk",
  "US_Virginia_Richmond",
  "US_Virginia_Roanoke",
  "US_Washington_Coast",
  "US_Washington_Seattle",
  "US_Washington_Yakima",
  "US_West Virginia",
  "US_Wisconsin_Eau Claire",
  "US_Wisconsin_Madison",
  "US_Wisconsin_Milwaukee",
  "US_Wisconsin_North",
  "US_Wyoming"
};
}  // namespace

namespace ads
{
Skyeng::Skyeng(Delegate & delegate)
  : DownloadOnMapContainer(delegate)
{
  AppendSupportedUserLanguages(kSupportedLanguages);
  AppendSupportedCountries(kSupportedCountries);
}

std::string Skyeng::GetBannerInternal() const
{
  return "http://promo.skyeng.ru/mapsme-adult";
}
}  // namespace ads
