#include "partners_api/ads/tinkoff_allairlines_ads.hpp"

namespace
{
std::initializer_list<std::string> const kSupportedLanguages = {"ru"};

std::initializer_list<storage::CountryId> const kSupportedCountries = {
  "Afghanistan",
  "Algeria",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Botswana",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Campo de Hielo Sur",
  "Cape Verde",
  "Caribisch Nederland",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "Colombia",
  "Comoros",
  "Congo-Brazzaville",
  "Congo-Kinshasa",
  "Cook Islands",
  "Costa Rica",
  "Cote dIvoire",
  "Djibouti",
  "Dominica",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Federated States of Micronesia",
  "Fiji",
  "Finland",
  "Gabon",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Iceland",
  "India",
  "Iraq",
  "Isle of Man",
  "Jamaica",
  "Japan",
  "Jersey",
  "Kazakhstan",
  "Kenya",
  "Kingdom of Lesotho",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Lebanon",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Mali",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mongolia",
  "Montserrat",
  "Mozambique",
  "Myanmar",
  "Nagorno-Karabakh",
  "Namibia",
  "Nauru",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "North Korea",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "People's Republic of China",
  "Peru",
  "Pitcairn Islands",
  "Poland",
  "Qatar",
  "Republic of Kosovo",
  "Rwanda",
  "Sahrawi Arab Democratic Republic",
  "Saint Barthelemy",
  "Saint Helena Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Solomon Islands",
  "Somalia",
  "South Georgia and the South Sandwich Islands",
  "South Ossetia",
  "South Sudan",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Thailand",
  "The Bahamas",
  "The Gambia",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United States Virgin Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Willis Island",
  "Yemen",
  "Zambia",
  "Zimbabwe"
};

std::initializer_list<storage::CountryId> const kSupportedUserPosCountries = {"Russian Federation"};
}  // namespace

namespace ads
{
TinkoffAllAirlines::TinkoffAllAirlines(Delegate & delegate)
  : DownloadOnMapContainer(delegate)
{
  AppendSupportedUserLanguages(kSupportedLanguages);
  AppendSupportedCountries(kSupportedCountries);
  AppendSupportedUserPosCountries(kSupportedUserPosCountries);
}

std::string TinkoffAllAirlines::GetBannerInternal() const
{
  return "https://www.tinkoff.ru/cards/credit-cards/all-airlines/form/?"
         "promo_code=MAPSME&utm_source=mapsme_allairlines&utm_medium=dsp.fix";
}
}  // namespace ads
