#!/usr/bin/env bash
#
# Refreshes the Boost headers in the 3party/boost_headers submodule from an
# upstream Boost checkout. Only maintainers need this; contributors just get the
# headers with the submodule.
#
# Usage: tools/unix/update_boost_headers.sh <boost-tag-or-commit>
#   e.g. tools/unix/update_boost_headers.sh boost-1.93.0
#
# The upstream superproject is cloned outside the repository (../boost-upstream
# by default, override with BOOST_SRC) so that several organicmaps worktrees can
# share one copy and it never shows up in git status.
#
set -euo pipefail

die() { echo "Error: $*" >&2; exit 1; }

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DEST="$REPO_ROOT/3party/boost_headers"
BOOST_SRC="${BOOST_SRC:-$(dirname "$REPO_ROOT")/boost-upstream}"
VERSION="${1:-}"

[ -n "$VERSION" ] || die "usage: $0 <boost-tag-or-commit>   (e.g. boost-1.93.0)"
[ -e "$DEST/.git" ] || die "$DEST is not checked out, run: git submodule update --init $DEST"

DEST_BRANCH="$(git -C "$DEST" symbolic-ref --quiet --short HEAD || true)"
[ -n "$DEST_BRANCH" ] || die "$DEST is detached, run from the repository root:
git -C 3party/boost_headers switch master"

dest_dirty="$(git -C "$DEST" status --porcelain --untracked-files=all)"
[ -z "$dest_dirty" ] || die "$DEST has local changes, refusing to overwrite or stage them:
$dest_dirty"

if [ ! -d "$BOOST_SRC/.git" ]; then
  echo "Cloning Boost into $BOOST_SRC (this takes a while)."
  # Clone only the superproject here. The required library submodules are
  # initialized after checking out the requested revision.
  git clone --filter=blob:none https://github.com/boostorg/boost.git "$BOOST_SRC"
fi

check_source_clean()
{
  local source_dirty
  source_dirty="$(git -C "$BOOST_SRC" status --porcelain --untracked-files=all --ignore-submodules=none -- \
    libs LICENSE_1_0.txt)"
  [ -z "$source_dirty" ] || die "$BOOST_SRC has local changes in copied inputs, refusing to continue:
$source_dirty"
}

# Check before changing revisions so local work cannot be overwritten, and
# again after updating submodules so only pristine upstream inputs are copied.
check_source_clean

echo "Checking out $VERSION in $BOOST_SRC."
git -C "$BOOST_SRC" fetch --tags --prune origin
git -C "$BOOST_SRC" checkout "$VERSION"
# Only libs/ holds headers; tools/ and doc/ are not needed to produce the tree.
git -C "$BOOST_SRC" submodule update --init --filter=blob:none --jobs 8 -- libs

# An uninitialised submodule is an empty directory, which would silently drop
# that library's headers from the copy below instead of failing.
submodules="$(git -C "$BOOST_SRC" submodule status -- libs)"
uninitialised="$(printf '%s\n' "$submodules" | grep '^-' || true)"
[ -z "$uninitialised" ] || die "these Boost submodules are not checked out:
$uninitialised"

# Other superproject paths are irrelevant because they are neither updated nor
# copied.
check_source_clean

REVISION="$(git -C "$BOOST_SRC" rev-parse "$VERSION^{commit}")"

# Boost's own boost/ directory is a symlink farm generated by "b2 headers".
# Rather than bootstrapping b2, reproduce it with a plain copy. Enumerating the
# current revision's submodules prevents a library removed upstream from being
# copied out of a stale checkout directory left by an earlier revision.
#   local all-headers =
#       [ MATCH .*libs/(.*)/include/boost : [ glob libs/*/include/boost libs/*/*/include/boost ] ] ;
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/boost"
while read -r _ path _; do
  [ -d "$BOOST_SRC/$path/include/boost" ] || continue
  rsync -a "$BOOST_SRC/$path/include/boost/" "$STAGE/boost/"
done <<< "$submodules"
[ -f "$STAGE/boost/version.hpp" ] || die "no boost/version.hpp in the staged tree, refusing to update $DEST"

if [ -d "$DEST/boost" ]; then
  before="$(find "$DEST/boost" -type f | wc -l | tr -d ' ')"
else
  before=0
fi

# --delete removes headers that no longer exist upstream; otherwise a stale
# header could remain available and hide an incomplete update.
rsync -a --delete "$STAGE/boost/" "$DEST/boost/"
cp "$BOOST_SRC/LICENSE_1_0.txt" "$DEST/LICENSE_1_0.txt"
cat > "$DEST/SOURCE_REVISION" <<EOF
# Upstream https://github.com/boostorg/boost superproject commit these headers
# were generated from by tools/unix/update_boost_headers.sh in organicmaps.
$REVISION
EOF

git -C "$DEST" add -A -- boost LICENSE_1_0.txt SOURCE_REVISION
# A global core.excludesFile can hide files from "git add" without a word, so
# make sure the index really got everything that is on disk.
missing="$(comm -23 \
  <(cd "$DEST" && find boost -type f | LC_ALL=C sort) \
  <(git -C "$DEST" ls-files boost | LC_ALL=C sort))"
[ -z "$missing" ] || die "these files were not staged, most likely hidden by an ignore rule:
$missing"

echo
echo "$(grep -m1 'define BOOST_LIB_VERSION' "$DEST/boost/version.hpp")"
echo "Headers: $before -> $(find "$DEST/boost" -type f | wc -l | tr -d ' ')"
git -C "$DEST" diff --cached --shortstat
cat <<EOF

Review the staged diff in $DEST, then:

  git -C 3party/boost_headers commit -s -m "Update Boost to X.Y.Z"
  git -C 3party/boost_headers push -u origin "$DEST_BRANCH"
  git add 3party/boost_headers && git commit -s -m "[3party] Update Boost to X.Y.Z"

Push boost_headers before the organicmaps commit, otherwise the new submodule
revision will not resolve for anyone else.
EOF
