@objc protocol IFonts {
  var regular9: UIFont { get }
  var regular10: UIFont { get }

  var regular11: UIFont { get }
  var regular12: UIFont { get }
  var regular13: UIFont { get }
  var regular14: UIFont { get }
  var regular15: UIFont { get }
  var regular16: UIFont { get }
  var regular17: UIFont { get }
  var regular18: UIFont { get }
  var regular20: UIFont { get }
  var regular24: UIFont { get }
  var regular32: UIFont { get }
  var regular52: UIFont { get }
  var medium9: UIFont { get }
  var medium10: UIFont { get }
  var medium12: UIFont { get }
  var medium14: UIFont { get }
  var medium16: UIFont { get }
  var medium17: UIFont { get }
  var medium18: UIFont { get }
  var medium20: UIFont { get }
  var medium24: UIFont { get }
  var medium28: UIFont { get }
  var medium36: UIFont { get }
  var medium40: UIFont { get }
  var medium44: UIFont { get }
  var light10: UIFont { get }
  var light12: UIFont { get }
  var light16: UIFont { get }
  var light17: UIFont { get }
  var bold12: UIFont { get }
  var bold14: UIFont { get }
  var bold16: UIFont { get }
  var bold17: UIFont { get }
  var bold18: UIFont { get }
  var bold20: UIFont { get }
  var bold22: UIFont { get }
  var bold24: UIFont { get }
  var bold28: UIFont { get }
  var bold34: UIFont { get }
  var bold36: UIFont { get }
  var bold48: UIFont { get }
  var heavy17: UIFont { get }
  var heavy20: UIFont { get }
  var heavy32: UIFont { get }
  var heavy38: UIFont { get }
  var italic16: UIFont { get }
  var semibold12: UIFont { get }
  var semibold14: UIFont { get }
  var semibold15: UIFont { get }
  var semibold16: UIFont { get }
  var semibold18: UIFont { get }
}
