package com.mapswithme.maps.discovery;

public enum DiscoveryUserEvent
{
  HOTELS_CLICKED,
  ATTRACTIONS_CLICKED,
  CAFES_CLICKED,
  LOCALS_CLICKED,
  MORE_HOTELS_CLICKED,
  MORE_ATTRACTIONS_CLICKED,
  MORE_CAFES_CLICKED,
  MORE_LOCALS_CLICKED
}
