package app.organicmaps.sdk.location;

import static android.os.Build.VERSION.SDK_INT;

import android.location.Location;
import android.os.Build;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public class LocationCompatExtractor
{
  public record AltitudeAndAccuracy(double altitude, float accuracy) {}
  public record SpeedAndAccuracy(float speed, float accuracy) {}
  public record BearingAndAccuracy(float bearing, float accuracy) {}

  @Nullable
  public static AltitudeAndAccuracy getAltitudeFromLocation(@NonNull Location location)
  {
    /// All locations generated by the LocationManager include horizontal accuracy.
    final float defaultVerticalAccuracyMeters = location.hasAccuracy() ? location.getAccuracy() * 2.f : 20.f;
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE && location.hasMslAltitude())
      return new AltitudeAndAccuracy(location.getMslAltitudeMeters(), location.hasMslAltitudeAccuracy()
                                                                          ? location.getMslAltitudeAccuracyMeters()
                                                                          : defaultVerticalAccuracyMeters);

    if (!location.hasAltitude())
      return null;

    if (SDK_INT >= 26 && location.hasVerticalAccuracy())
      return new AltitudeAndAccuracy(location.getAltitude(), location.getVerticalAccuracyMeters());

    return new AltitudeAndAccuracy(location.getAltitude(), defaultVerticalAccuracyMeters);
  }

  @Nullable
  static SpeedAndAccuracy getSpeedFromLocation(@NonNull Location location)
  {
    if (!location.hasSpeed())
      return null;

    if (SDK_INT >= 26 && location.hasSpeedAccuracy())
      return new SpeedAndAccuracy(location.getSpeed(), location.getSpeedAccuracyMetersPerSecond());

    // Default accuracy value when real accuracy is not available.
    return new SpeedAndAccuracy(location.getSpeed(), 5.0f);
  }

  @Nullable
  static BearingAndAccuracy getBearingFromLocation(@NonNull Location location)
  {
    if (!location.hasBearing())
      return null;

    if (SDK_INT >= 26 && location.hasBearingAccuracy())
      return new BearingAndAccuracy(location.getBearing(), location.getBearingAccuracyDegrees());

    // Default accuracy value when real accuracy is not available.
    return new BearingAndAccuracy(location.getBearing(), 10.0f);
  }
}
