package app.organicmaps.sdk.location;

import android.location.Location;
import android.os.Build;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public class LocationCompatExtractor
{
  public record Altitude(double altitude, float accuracy) {
    public Altitude
    {
      assert accuracy > 0;
    }
  }
  public record Speed(float speed, float accuracy) {
    public Speed
    {
      assert speed >= 0;
    }
  }
  public record Bearing(float bearing, float accuracy) {
    public Bearing
    {
      assert bearing >= 0;
    }
  }

  private static float getDefaultAltitudeAccuracy(@NonNull Location location)
  {
    // All locations generated by the LocationManager include horizontal accuracy, according to docs.
    // ...but it is Android, baby. Check it. Just in case.
    if (location.hasAccuracy())
      return location.getAccuracy() * 2.f;
    return 20.f;
  }

  @Nullable
  public static Altitude getAltitude(@NonNull Location location)
  {
    // MSL altitude without accuracy is extremely unlikely.
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE && location.hasMslAltitude())
      return new Altitude(location.getMslAltitudeMeters(), location.hasMslAltitudeAccuracy()
                                                               ? location.getMslAltitudeAccuracyMeters()
                                                               : getDefaultAltitudeAccuracy(location));

    if (!location.hasAltitude())
      return null;

    if (Build.VERSION.SDK_INT >= 26 && location.hasVerticalAccuracy())
      return new Altitude(location.getAltitude(), location.getVerticalAccuracyMeters());

    return new Altitude(location.getAltitude(), getDefaultAltitudeAccuracy(location));
  }

  @Nullable
  static Speed getSpeed(@NonNull Location location)
  {
    if (!location.hasSpeed())
      return null;

    if (Build.VERSION.SDK_INT >= 26 && location.hasSpeedAccuracy())
      return new Speed(location.getSpeed(), location.getSpeedAccuracyMetersPerSecond());

    // Default accuracy value when real accuracy is not available.
    return new Speed(location.getSpeed(), 5.0f);
  }

  @Nullable
  static Bearing getBearing(@NonNull Location location)
  {
    if (!location.hasBearing())
      return null;

    if (Build.VERSION.SDK_INT >= 26 && location.hasBearingAccuracy())
      return new Bearing(location.getBearing(), location.getBearingAccuracyDegrees());

    // Default accuracy value when real accuracy is not available.
    return new Bearing(location.getBearing(), 10.0f);
  }
}
